# Menggunakan Docker Compose versi 2 atau lebih
version: "3.7"

services:
  # Service item-app
  item-app:
   # Menggunakan image item-app dari Github Packages
   image: ghcr.io/firmanmardiyanto/item-app:v1
   # Port mapping ke port 80 
   ports:
     - 80:8080
   # Dependensi ke service item-db
   depends_on:
     - "item-db"
   # Restart policy
   restart: always
  # Service item-db  
  item-db:
    # Menggunakan image mongo:3
    image: mongo:3
    # Memakai volume app-db dengan target /data/db
    volumes:
      - app-db:/data/db
    # Restart policy
    restart: always
# Membuat volume app-db
volumes:
  app-db: